version: '2'
services:
  factorio:
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=2.0.42
        - SHA256=b5b8b8bdc915e67dbc1710cd3d6aa6802d397b7c0f47db07da8acf39d5bd6376
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
      #    environment:
      #      - PUID=1000
      #      - PGID=1000
      #      - UPDATE_MODS_ON_START=true
      #      - USERNAME=FactorioUsername
      #      - TOKEN=FactorioToken
      #      - PORT=34198
      #      - PRESET=deathworld
      #      - ADDR=::1
#    # Uncomment the following line to enable the use of the host's network stack,
#    # which may be necessary for some setups like NAS or when using some proxy service like firewall rules.
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
