name: Docker build & push

on:
  push:
    branches:
      - master
    paths:
      - buildinfo.json
  # workaround for #526
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: build and push
        if: ${{ env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != '' }}
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          sed -i "s/__TOKEN__/${{ secrets.TOKEN }}/g" docker/files/update_mods.sh
          ./build.py --push-tags --multiarch
